name: publish
on:
  push:
    branches: [main, dagger]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Dagger Function to build and publish
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: publish --src=. --actor=dirkfaust --token=env:DOCKER_PASSWORD
        env:
          DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
